version: "3.9"

volumes:
  wordpress-mysql:
  wordpress-www:

services:
  
  #MySQL Database image
  database:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "8001:80"
    environment:
      MYSQL_ROOT_PASSWORD: my_password_1234789
      MYSQL_DATABASE: my_wp_database
      MYSQL_USER: my_wp_user
      MYSQL_PASSWORD: my_wp_user_password
    volumes:
      - wordpress-mysql:/var/lib/mysql

  #WordPress image based on Apache
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: my_wp_user
      WORDPRESS_DB_PASSWORD: my_wp_user_password
      WORDPRESS_DB_NAME: my_wp_database
    volumes:
      - wordpress-www:/var/www/html
